### ISSUE TITLE
Keymap Customization

### ISSUE THREAD

**Issue by atticusrussell** [MCJack123/ArduinoADB#1]
Hi there. Thank you for writing this! Do you have any suggestions as how I would go about editing the keymap? Specifically I want to swap the gui keys with the alt keys. I'm unsure if I should edit the keymap.h file or the adb_to_usb.ino. 
I know that there is a website on which to configure the keymap for the TMK version of this that uses the atmega32u4 and atmega32u2 - but i imagine it would be wrong for this 16u2?
http://www.tmk-kbd.com/tmk_keyboard/editor/unimap/?adb_usb

**Comment by MCJack123** [comment]
`keymap.h` contains a list of conversions from ADB keycodes to USB keycodes. It is ordered by ADB codes, so the first entry is ADB keycode 0, the next is for code 1, etc. ADB keycodes are listed [around this page](https://github.com/tmk/tmk_keyboard/wiki/Apple-Desktop-Bus#scan-codes), and USB keycodes can be found [in the USB HID specification](https://usb.org/sites/default/files/hut1_3_0.pdf#page89).

However, because of how USB handles modifier keys, you'll need to adjust the `adb_to_usb.ino` file if you want to swap modifier keys. For your case, you can swap around lines 22 and 26, and 30 and 34. That should produce the result you're looking for.

The link you provided indeed would not work here, as that modifies the firmware directly, which this code does not rely on (the USB keyboard firmware provided does not handle any of the ADB conversion, so it can't be used with the ADB keymap rewriter).

**Comment by MCJack123** [comment]
@atticusrussell 

> Some of the keys work but it mainly outputs incorrect keys on the rest of the keyboard and somewhat seems as if the super (windows) key is stuck down.

Oh, I just checked the code again, and you also need to update lines 58-73 in the same way as above - the first lines are for releasing the key, but the other part handles pressing the key.

> you mentioned keymap.h - would I also need to modify that header file in addition to the noted modification to the adb_to_usb.ino to make this work?

The keymap is only used for non-modifier keys, so you don't need to mess with that if you don't need to rearrange the actual key layout.
